### PR TITLE
fix tests

### PR DESCRIPTION
**Pull request by i-ghost**

### CODE REVIEW

**Comment by i-ghost** [comment]
GitHub being real fancy with this test integration.

**Comment by Lagg** [comment]
Holy crap they are. And zis isn't  generally how I do my import glue, but I guess it works out better than using exceptions for flow control. Thanks

**Comment by Lagg** [comment]
Also i-ghost you need to associate yer git address with github so further fanciness can be achieved.

**Comment by i-ghost** [comment]
Done and done.

**Pull request merged**
